[package]
name = "kubelet"
version = "0.1.0"
authors = [
    "Matt Butcher <matt.butcher@microsoft.com>",
    "Matthew Fisher <matt.fisher@microsoft.com>",
    "Radu Matei <radu.matei@microsoft.com>",
    "Taylor Thomas <taylor.thomas@microsoft.com>",
    "Brian Ketelsen <Brian.Ketelsen@microsoft.com>",
    "Brian Hardock <Brian.Hardock@microsoft.com>",
    "Ryan Levick <rylevick@microsoft.com>",
]
edition = "2018"

[dependencies]
async-trait = "0.1.24"
failure = "0.1"
futures = "0.3.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hyper = "0.13.3"
log = "0.4"
reqwest = "0.10.4"
tokio  = { version = "0.2.13" }
kube = { version = "0.28.0"  }
k8s-openapi = { version = "0.7.1", default-features = false, features = ["v1_17"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { git = "https://github.com/clap-rs/clap", features = ["wrap_help"], optional = true }
hostname = "^0.3"

[features]
default = []
cli = ["clap"]
