name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          wget https://github.com/casey/just/releases/download/v0.5.8/just-v0.5.8-x86_64-unknown-linux-musl.tar.gz
          tar -xzf just-v0.5.8-x86_64-unknown-linux-musl.tar.gz -C /tmp
          /tmp/just build
          /tmp/just test
