name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: "ubuntu-latest",
              url: "https://github.com/casey/just/releases/download/v0.5.8/just-v0.5.8-x86_64-unknown-linux-musl.tar.gz",
              name: "just",
              pathInArchive: "just",
            }
          - {
              os: "macos-latest",
              url: "https://github.com/casey/just/releases/download/v0.5.8/just-v0.5.8-x86_64-apple-darwin.tar.gz",
              name: "just",
              pathInArchive: "just",
            }
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/configurator@v0.0.1
        with:
          name: ${{ matrix.config.name }}
          url: ${{ matrix.config.url }}
          pathInArchive: ${{ matrix.config.pathInArchive }}
      - name: Build
        run: |
          just build
          just test
