[package]
name = "wasi-provider"
version = "0.1.0"
authors = [
    "Matt Butcher <matt.butcher@microsoft.com>",
    "Matthew Fisher <matt.fisher@microsoft.com>",
    "Radu Matei <radu.matei@microsoft.com>",
    "Taylor Thomas <taylor.thomas@microsoft.com>",
    "Brian Ketelsen <Brian.Ketelsen@microsoft.com>",
    "Brian Hardock <Brian.Hardock@microsoft.com>",
    "Ryan Levick <rylevick@microsoft.com>",
]
edition = "2018"

[dependencies]
async-trait = "0.1.24"
kube = { version = "0.28.0" }
log = "0.4"
failure = "0.1"
wasmtime = "0.12"
wasmtime-wasi = "0.12"
wasi-common = "0.12"
tempfile = "3.1"
serde = "1.0"
serde_json = "1.0"
kubelet = { path = "../kubelet", version = "0.1.0" }
wat = "1.0"
tokio = { version = "0.2.13", features = ["fs", "stream", "macros", "io-util"] }

[dev-dependencies]
k8s-openapi = { version = "0.7.1", features = ["v1_17"] }
